apiVersion: v1
kind: Service
metadata:
  name: redis-cache-production
  labels:
    app: redis-cache-production
    env: production
    namespace: default
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-cache-production
